sudo: false

git:
  depth: 1

branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js

# cache node modules
cache:
  directories:
    - $HOME/.npm
    - node_modules

matrix:
  fast_finish: true
  include:
    - node_js: '10'
      script: npm run $JOB_PART
      env: JOB_PART=pretest
    - node_js: '10'
      script: npm run $JOB_PART
      env: JOB_PART=test-only
    - node_js: '9'
      script: npm run $JOB_PART
      env: JOB_PART=test-only
    - node_js: '8'
      script: npm run $JOB_PART
      env: JOB_PART=test-only
    - node_js: '6'
      script: npm run $JOB_PART
      env: JOB_PART=test-only
      sudo: required

before_install:
  - npm i -g npm
  - nvm --version
  - node --version
  - npm --version
