name: CI

on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - "**"

env:
  CI: true

jobs:
  lint:
    name: Lint on Node.js ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [12]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install latest npm
        run: npm install --global npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run pretest

  test:
    name: Test on Node.js ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [10, 12, 13]
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - name: next
            node: 13
            next: true

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install latest npm
        run: npm install --global npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Install webpack@next
        run: npm i webpack@next
        if: ${{ runner.next }}

      - name: Test
        run: npm run test:only
